/**
 * Author: Rahul Shetty
 * Date: 09/10/2019
 *
 * List all the action types
 * @flow
 */

export const USER_LOGOUT = 'USER_LOGOUT';

export const SEARCH = 'SEARCH';

export const RECIPE_TYPES = {
  GET_RECIPE_CATEGORIES_REQUEST: 'GET_RECIPE_CATEGORIES_REQUEST',
  GET_RECIPE_CATEGORIES_SUCCESS: 'GET_RECIPE_CATEGORIES_SUCCESS',
  GET_RECIPE_CATEGORIES_ERROR: 'GET_RECIPE_CATEGORIES_ERROR',
};
